# This workflow builds docstringify on Mac, Linux, and Windows for
# multiple versions of Python to confirm it can be properly installed.
#
# Based on https://github.com/stefmolin/data-morph/blob/main/.github/workflows/ci.yml
#
# Author: Stefanie Molin

name: CI

on:
  push:
    branches: [ "main" ]
    paths:
      - '**'
      - '!.github/**'
      - '.github/workflows/ci.yml'
    tags: [ "v*" ]

  pull_request:
    paths:
      - '**'
      - '!.github/**'
      - '.github/workflows/ci.yml'

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build with Python ${{ matrix.python-version }} on ${{ matrix.os }}

    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -e {0}

    strategy:
        fail-fast: false
        matrix:
            os: [macos-latest, ubuntu-latest, windows-latest]
            python-version: ["3.11", "3.12", "3.13", "3.14"]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install docstringify
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools --upgrade
          python -m pip install .

      - name: Check entry point
        run: docstringify --version

      - name: Install dev dependencies
        run: python -m pip install --group dev

      - name: Check that the docstringify-edit pre-commit hook is available
        run: pre-commit try-repo . docstringify-edit

      - name: Check that the docstringify-suggest pre-commit hook is available
        run: pre-commit try-repo . docstringify-suggest

      # this is the only hook that works without an additional arg so we can test it like this
      - name: Validate the docstringify-check pre-commit hook
        run: pre-commit try-repo . docstringify-check --all-files

      - name: Run tests
        run: pytest
